#!/bin/sh

start() {
	echo "Starting aesdsocket"
	start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- '-d'
}
stop() {
	echo "Stopping aesdsocket"
	start-stop-daemon -K -n aesdsocket
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
